### ISSUE TITLE
Encoded non-breaking space in config

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessPageFieldSelectCreator#2]
Hi Adrian,

I'm seeing encoded non-breaking spaces in the module config:

![2019-03-09_100650](https://user-images.githubusercontent.com/1538852/54055839-17c4c100-4253-11e9-86d8-cef466fd6050.png)

**Comment by adrianbj** [comment]
Hey @Toutouwai - Thanks for the report, but I don't know why - it looks fine here. 

![image](https://user-images.githubusercontent.com/871211/54056087-e50fbf80-41a3-11e9-8df5-734ab3579d97.png)

The reason for those stupid `&nbsp;`'s is because of the file compiler bug that would otherwise make it: \ProcessWire\pages(PageArray)

Any ideas why they are encoded for you and not me?

**Comment by Toutouwai** [comment]
It's weird - I have one installation where the ampersand at the start of `&nbps;` is getting encoded and another where it isn't. Same PW version, same module version.

The issue relates to the use of the `__()` translation function. If I remove the translation function call from one of the option strings there is no encoding issue for that option.

I'm thinking it has something to do with a recent change to the function introduced in PW 3.0.125 - documented here: https://processwire.com/api/ref/functions/__/

> Advanced features
> The following features are for specific cases and supported in ProcessWire 3.0.125+ only.
> 
> You can use this function to get or set specific options that affect future calls by specifying boolean true for the first argument, option name for the second argument, and option value for the third  argument. Currently there are just two options, “entityEncode” and “translations”. The “entityEncode” option enables you to control whether future calls return entity encoded text or not (see advanced examples).

So what seems to be happening is that at some point some code has called the translation function in a way that turns entity encoding on for all future calls to the function (!!?). If I var_dump `$options['entityEncode']` then sure enough it is `null` on the installation that is working as expected and `true` on the installation that is encoding the ampersand. The option persists because of the static keyword. This seems really undesirable and I don't understand the thinking behind it, but this is perhaps because I've never had a need to use this translation function.

Not sure what can be done about this. Maybe you don't want to change the way you are defining translatable strings in the module, but I always use the `$this->_()` function which I think is unaffected by this issue. For class contexts it supposedly performs better too: https://processwire.com/docs/multi-language-support/code-i18n/#syntax-inside-a-class-vs-syntax-outside-of-a-class

**Comment by Toutouwai** [comment]
I've found the cause: https://github.com/processwire/processwire/blob/e427a03ff5dba70ff124a906d7ad587c3e03639b/wire/core/ProcessWire.php#L283-L287

Surely this has the potential to break a lot of existing modules and site code?

**Comment by Toutouwai** [comment]
I was wrong about `$this->_()` being unaffected - the method is just calling `__()` behind the scenes. So it seems that for installations after Jan 10 2019 you cannot use entities within translatable strings or they will get double-encoded.

Maybe Ryan could be convinced to change...

```php
if($config->installed >= 1547136020) {
	// installations Jan 10, 2019 and onwards:
	// make the __('text') translation function return entity encoded text, whether translated or not
	__(true, 'entityEncode', true);
}
```
...to...
```php
if($config->installed >= 1547136020) {
	// installations Jan 10, 2019 and onwards:
	// make the __('text') translation function return entity encoded text if not already encoded, whether translated or not
	__(true, 'entityEncode', 1);
}
```

**Comment by Toutouwai** [comment]
I raised an issue in the core repo here: https://github.com/processwire/processwire-issues/issues/827

**Comment by adrianbj** [comment]
Hey @Toutouwai - thanks for all the troubleshooting. I guess we'll see what Ryan has to say. If he's not willing to make that change, not really sure what we can all do :)

**Comment by Toutouwai** [comment]
Ryan commented:

> translatable strings are not intended to be defined with HTML or entities in them, as neither would survive translation in any version of PW

This sounds like an important consideration, so perhaps when an entity needs to be used within a translatable string either one of the following two options should be used:

```php
__('Multiple pages', __FILE__) . '&nbsp;' . __('(PageArray)', __FILE__)
```
or
```php
sprintf(__('Multiple pages%s(PageArray)', __FILE__), '&nbsp;')
```

Let me know your thoughts and if the options above sound okay I'll close the other issue.

**Comment by adrianbj** [comment]
Hi @Toutouwai - thanks for checking in with Ryan on this - much appreciated.

Of your two options, I don't really like the first because it would mean two separate strings for translators to deal with (although I am not really sure if any PW modules are ever translated). For some reason I haven't really ever been much of a `sprintf` user - it never comes to mind as the first / best thing to use, even though it probably often is. It certainly seems to work well, even though all of this is a stupid hack :)

Maybe it's just better if I remove the `&nbsp;` and we can deal with the FileCompiler bug?

Anyway, in the end I went with your `sprintf` approach and I have committed the change (no version number bump for now).

I am happy enough if you are - feel free to close this when you're ready.

**Comment by Toutouwai** [comment]
Neither of the two options are ideal, I agree.

I took a look at the FileCompiler code and the scenario that is triggering the unwanted changes in this case is the regex that will kick in whenever any of the following...

<details>
  <summary>Click to expand</summary>
_wirepagesapi<br>
_wiredataapi<br>
wirepages<br>
wirepage<br>
wireconfig<br>
wiremodules<br>
wireuser<br>
wireusers<br>
wiresession<br>
wirefields<br>
wiretemplates<br>
wiredatabase<br>
wirepermissions<br>
wireroles<br>
wiresanitizer<br>
wiredatetime<br>
wirefiles<br>
wirecache<br>
wirelanguages<br>
wireinput<br>
wireinputget<br>
wireinputpost<br>
wireinputcookie<br>
wirelog<br>
wireprofiler<br>
wireurls<br>
wirepaths<br>
wiresetting<br>
_wirefunctionsapi<br>
wire<br>
wireinstance<br>
fuel<br>
wireencodejson<br>
wiredecodejson<br>
wireminarray<br>
wiremkdir<br>
wirermdir<br>
wirechmod<br>
wirecopy<br>
wireunzipfile<br>
wirezipfile<br>
wiresendfile<br>
wirerelativetimestr<br>
wiremail<br>
wirepopulatestringtags<br>
wiretempdir<br>
wirerenderfile<br>
wireincludefile<br>
wiredate<br>
wireiconmarkup<br>
wireiconmarkupfile<br>
wirebytesstr<br>
wireclassname<br>
wireclassexists<br>
wiremethodexists<br>
wireclassimplements<br>
wireclassparents<br>
wireinstanceof<br>
wireiscallable<br>
wirecount<br>
wireregion<br>
wirearray<br>
wiredata<br>
pagearray<br>
tabindent<br>
__<br>
_x<br>
_n<br>
pages<br>
page<br>
config<br>
modules<br>
user<br>
users<br>
session<br>
fields<br>
templates<br>
database<br>
permissions<br>
roles<br>
sanitizer<br>
datetime<br>
files<br>
cache<br>
languages<br>
input<br>
inputget<br>
inputpost<br>
inputcookie<br>
urls<br>
paths<br>
profiler<br>
region<br>
setting<br>
dump<br>
dumpe<br>
bdump<br>
tracyunavailable<br>
debugall<br>
bardump<br>
bardumpbig<br>
dumpbig<br>
timer<br>
firelog<br>
addbreakpoint<br>
templatevars<br>
da<br>
bd<br>
bdb<br>
d<br>
db<br>
l<br>
t<br>
fl<br>
bp<br>
buster<br>
</details>

...are followed by an open parenthesis, with or without any space character in between.
It's a shame about the space characters being matched in the pattern because otherwise this would avoid many of the cases where an unwanted replacement occurs. In reality I don't think anyone ever inserts space between a function name and the open parenthesis, but the trouble is that it's still valid PHP to do so.

Another way to avoid this compiler issue is to use some other character instead of the parenthesis - e.g. use square brackets instead. But this is not ideal either.

Hopefully the FileCompiler will be dropped from the core before too long.
