### ISSUE TITLE
File Compiler interferes with field label

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessPageFieldSelectCreator#3]
The File Compiler is messing with one of the field labels:

![2019-09-22_112942](https://user-images.githubusercontent.com/1538852/65380293-507a4280-dd2c-11e9-8f6c-c5faa9916fc9.png)

Harking back to our discussion [here](https://github.com/adrianbj/ProcessPageFieldSelectCreator/issues/2), one solution would be to change...

```php
$f->label = __('Child pages (select options)', __FILE__);
```

...to...

```php
$f->label = sprintf(__('Child pages%s(select options)', __FILE__), '&nbsp;');
```

**Comment by Toutouwai** [comment]
Or include the namespace and make PW3 required for the next update of the module. It feels like PW2 is ancient history now :-)

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I typically just do:
```
$f->label = __('Child pages&nbsp;(select options)', __FILE__);
```

Is there any need for the `sprintf()` ?

**Comment by adrianbj** [comment]
I don't remember why we had to start using the `sprintf` approach but I see I use it throughout this module, so obviously went with your suggestion - thanks.

**Comment by Toutouwai** [comment]
Sorry, I missed your reply. The reason for `sprintf` is discussed in the earlier issue I linked to in the first post.

Thanks for the fix.
