### ISSUE TITLE
Creation disallowed despite not actually creating Page field

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessPageFieldSelectCreator#4]
Hi Adrian,

I minor issue: if you have "Don't actually create the page field" checked the template/page creation fails if there is an existing field matching the "Field label". Could that check be skipped in this instance seeing as no field will be created?

**Comment by adrianbj** [comment]
Good catch - thanks!

Should be fixed in the latest version.

**Comment by Toutouwai** [comment]
Thanks for the speedy fix!
